const devices = [
  {
    _bluetoothModule: {
      _eventEmitter: [NativeEventEmitter],
      _nativeModule: [Object],
    },
    _nativeDevice: {
      address: '41:42:24:79:19:BD',
      bonded: true,
      extra: [Object],
      id: '41:42:24:79:19:BD',
      name: 'Mi True Wireless EBs Basic_R',
    },
    address: '41:42:24:79:19:BD',
    bonded: true,
    deviceClass: undefined,
    extra: {},
    id: '41:42:24:79:19:BD',
    name: 'Mi True Wireless EBs Basic_R',
    rssi: undefined,
  },
  {
    _bluetoothModule: {
      _eventEmitter: [NativeEventEmitter],
      _nativeModule: [Object],
    },
    _nativeDevice: {
      address: '98:D3:61:F6:1B:86',
      bonded: true,
      extra: [Object],
      id: '98:D3:61:F6:1B:86',
      name: 'MIBT',
    },
    address: '98:D3:61:F6:1B:86',
    bonded: true,
    deviceClass: undefined,
    extra: {},
    id: '98:D3:61:F6:1B:86',
    name: 'MIBT',
    rssi: undefined,
  },
  {
    _bluetoothModule: {
      _eventEmitter: [NativeEventEmitter],
      _nativeModule: [Object],
    },
    _nativeDevice: {
      address: '5C:BA:EF:0C:DB:FE',
      bonded: true,
      extra: [Object],
      id: '5C:BA:EF:0C:DB:FE',
      name: 'julian-pc',
    },
    address: '5C:BA:EF:0C:DB:FE',
    bonded: true,
    deviceClass: undefined,
    extra: {},
    id: '5C:BA:EF:0C:DB:FE',
    name: 'julian-pc',
    rssi: undefined,
  },
  {
    _bluetoothModule: {
      _eventEmitter: [NativeEventEmitter],
      _nativeModule: [Object],
    },
    _nativeDevice: {
      address: 'BC:2D:EF:B5:DB:88',
      bonded: true,
      extra: [Object],
      id: 'BC:2D:EF:B5:DB:88',
      name: 'realme C3',
    },
    address: 'BC:2D:EF:B5:DB:88',
    bonded: true,
    deviceClass: undefined,
    extra: {},
    id: 'BC:2D:EF:B5:DB:88',
    name: 'realme C3',
    rssi: undefined,
  },
];
